name: Basic tests # Basically check that it can be run

on:
  pull_request:
    types: [ opened, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up android SDK
      uses: android-actions/setup-android@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - name: Run tests
      run: ./gradlew testDebugUnitTest
    - name: Build snapshot
      run: ./gradlew assembleDebug