# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "feature/snapshot-workflow" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up android SDK
      uses: android-actions/setup-android@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - name: Build snapshot
      run: |
        # gradle test
        gradle assembleRelease
    - name: Sign APK with debug key
      run: $(find ~/.android/Sdk/build-tools/*/apksigner | sort -r | grep -v rc | head -1) sign --ks ~/.android/debug.keystore --ks-pass pass:android --out app/build/outputs/apk/release/app-release-signed-debug-key.apk app/build/outputs/apk/release/app-release-unsigned.apk
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release-signed-debug-key.apk
